In [ ]:
import numpy as np

# Student Marks Management System

🎯 Objective: You are working with student marks data and need to prepare and organize it using NumPy arrays.Your goal is to create, modify, and analyze the data efficiently without using any external libraries.

🧠 Project Description: A school has recorded the marks of several students in different subjects.You are required to design a NumPy-based solution to store, manage, and process this data.Your tasks involve creating arrays, changing their shapes, combining data, performing modifications, and analyzing patterns — all using NumPy.

📋 Project Tasks: **Data Creation:**Create suitable arrays to represent students, subjects, and their marks.

**Data Exploration:**Explore the properties of these arrays — such as their dimensions, size, and structure.

**Data Transformation:**Perform necessary reshaping and reorganization of the data to suit various operations.

**Data Combination:**Merge or split arrays to simulate adding new students, new subjects, or reorganizing the dataset.

**Data Modification:**Apply operations to update marks, remove data, or identify unique information.

**Data Type Handling:**Demonstrate how the same data can exist in different data types and how changes affect results.

**Copy and View Behavior:**Show the difference between creating a full copy of an array and creating a view of the same data.



# Data Creation

In [ ]:
arr_std = np.array(["A","B","C","D"])
arr_sub = np.array(["S1","S2","S3","S4"])
arr_marks = np.array([[10,20,30,40],[15,60,70,80],[15,80,40,20],[25,40,50,60]])

# Data Exploration

In [ ]:
print(arr_std.ndim)
print(arr_sub.ndim)
print(arr_marks.ndim)

1
1
2


In [ ]:
print(arr_marks.shape)

(4, 4)


In [ ]:
print(arr_std.size)
print(arr_sub.size)
print(arr_marks.size)

4
4
16


# Data Transformation

In [ ]:
arr_subjects=np.repeat(arr_sub,4)

In [ ]:
arr_subjects = arr_subjects.reshape(4,4)

In [ ]:
arr_subjects = arr_subjects.T

In [ ]:
arr_subjects

array([['S1', 'S2', 'S3', 'S4'],
       ['S1', 'S2', 'S3', 'S4'],
       ['S1', 'S2', 'S3', 'S4'],
       ['S1', 'S2', 'S3', 'S4']], dtype='<U2')

# Data Combination

In [ ]:
new_std = np.array(['E'])
new_marks = np.array([[17,70,90,20]])
new_subjects = np.array([['S1','S2','S3','S4']])

In [ ]:
arr_std = np.concatenate((arr_std,new_std))
arr_std

array(['A', 'B', 'C', 'D', 'E'], dtype='<U1')

In [ ]:
arr_subjects = np.concatenate((arr_subjects,new_subjects))
arr_subjects

array([['S1', 'S2', 'S3', 'S4'],
       ['S1', 'S2', 'S3', 'S4'],
       ['S1', 'S2', 'S3', 'S4'],
       ['S1', 'S2', 'S3', 'S4'],
       ['S1', 'S2', 'S3', 'S4']], dtype='<U2')

In [ ]:
arr_marks = np.concatenate((arr_marks,new_marks))
arr_marks

array([[10, 20, 30, 40],
       [15, 60, 70, 80],
       [15, 80, 40, 20],
       [25, 40, 50, 60],
       [17, 70, 90, 20]])

In [ ]:
split_std = np.split(arr_std, 5)
split_sub = np.split(arr_subjects,5)

In [ ]:
split_std

[array(['A'], dtype='<U1'),
 array(['B'], dtype='<U1'),
 array(['C'], dtype='<U1'),
 array(['D'], dtype='<U1'),
 array(['E'], dtype='<U1')]

In [ ]:
split_sub

[array([['S1', 'S2', 'S3', 'S4']], dtype='<U2'),
 array([['S1', 'S2', 'S3', 'S4']], dtype='<U2'),
 array([['S1', 'S2', 'S3', 'S4']], dtype='<U2'),
 array([['S1', 'S2', 'S3', 'S4']], dtype='<U2'),
 array([['S1', 'S2', 'S3', 'S4']], dtype='<U2')]

# Data Modification

In [ ]:
len(arr_marks)

5

In [ ]:
for i in range(len(arr_marks)):
  for j in range(len(arr_marks[i])):
      if arr_marks[i,j] < 35:
        arr_marks[i,j] = arr_marks[i,j] + 5


arr_marks

array([[15, 25, 35, 40],
       [20, 60, 70, 80],
       [20, 80, 40, 25],
       [30, 40, 50, 60],
       [22, 70, 90, 25]])

In [ ]:
np.unique(arr_marks)

array([15, 20, 22, 25, 30, 35, 40, 50, 60, 70, 80, 90])

# Data Type Handling

In [ ]:
arr_marks.astype(dtype=float)

array([[15., 25., 35., 40.],
       [20., 60., 70., 80.],
       [20., 80., 40., 25.],
       [30., 40., 50., 60.],
       [22., 70., 90., 25.]])

In [ ]:
arr_marks.astype(dtype=str)

array([['15', '25', '35', '40'],
       ['20', '60', '70', '80'],
       ['20', '80', '40', '25'],
       ['30', '40', '50', '60'],
       ['22', '70', '90', '25']], dtype='<U21')

# Copy and View Behaviour

In [ ]:
new_arr = arr_subjects.copy()

In [ ]:
new_arr[0][1] = 'S9'

In [ ]:
new_arr

array([['S1', 'S9', 'S3', 'S4'],
       ['S1', 'S2', 'S3', 'S4'],
       ['S1', 'S2', 'S3', 'S4'],
       ['S1', 'S2', 'S3', 'S4'],
       ['S1', 'S2', 'S3', 'S4']], dtype='<U2')

In [ ]:
arr_subjects

array([['S1', 'S2', 'S3', 'S4'],
       ['S1', 'S2', 'S3', 'S4'],
       ['S1', 'S2', 'S3', 'S4'],
       ['S1', 'S2', 'S3', 'S4'],
       ['S1', 'S2', 'S3', 'S4']], dtype='<U2')

In [ ]:
new_arr = arr_subjects.view()
new_arr[1][2] = 'S8'
new_arr

array([['S1', 'S2', 'S3', 'S4'],
       ['S1', 'S2', 'S8', 'S4'],
       ['S1', 'S2', 'S3', 'S4'],
       ['S1', 'S2', 'S3', 'S4'],
       ['S1', 'S2', 'S3', 'S4']], dtype='<U2')

In [ ]:
arr_subjects

array([['S1', 'S2', 'S3', 'S4'],
       ['S1', 'S2', 'S8', 'S4'],
       ['S1', 'S2', 'S3', 'S4'],
       ['S1', 'S2', 'S3', 'S4'],
       ['S1', 'S2', 'S3', 'S4']], dtype='<U2')